In [86]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [87]:
gm2020 = r"C:\Users\jerzy\PycharmProjects\projekt_zal\dane2020\20210215_Gminy_2_za_2020.xlsx"
gm_ludnosc = r"C:\Users\jerzy\PycharmProjects\projekt_zal\Ludność.Stan i struktura_31.12.2020\tabela12.xls"
gm2019 = r'C:\Users\jerzy\PycharmProjects\projekt_zal\dane2019\20200214_Gminy_za_2019.xlsx'

pow2019 = r'C:\Users\jerzy\PycharmProjects\projekt_zal\dane2019\20200214_Powiaty_za_2019.xlsx'
pow2020 = r'C:\Users\jerzy\PycharmProjects\projekt_zal\dane2020\20210211_Powiaty_za_2020.xlsx'
pow_ludnosc = r'C:\Users\jerzy\PycharmProjects\projekt_zal\Ludność.Stan i struktura_31.12.2020\tabela05.xls'

wojewodztwa2019 = r'C:\Users\jerzy\PycharmProjects\projekt_zal\dane2019\20200214_Wojewodztwa_za_2019.xlsx'
wojewodztwa2020 = r'C:\Users\jerzy\PycharmProjects\projekt_zal\dane2020\20210211_Województwa_za_2020.xlsx'
wojewodztwa_ludnosc = r'C:\Users\jerzy\PycharmProjects\projekt_zal\Ludność.Stan i struktura_31.12.2020\tabela02.xls'

In [88]:
from projekt.gminy import *
from projekt.powiaty import *
from projekt.wojewodztwa import *

Poniżej tworzę pełne tabele ze wszystkimi informacjami osobno dla gmin, powiatów i województw

In [89]:
df_gm = gminy(gm2019, gm2020, gm_ludnosc)
df_pow = powiaty(pow2019,pow2020,pow_ludnosc, df_gm)
df_woj = wojewodztwa(wojewodztwa2019, wojewodztwa2020, wojewodztwa_ludnosc, df_pow)

Pełna tabela dla gmin

In [90]:
df_gm

,id,gmina,dochody 2019,dochody 2020,populacja,średni dochód 2019,średni dochód 2020,id2
0,0201011,Bolesławiec,42635709.0,40456699,38486.0,24395,23149,0201
1,0201022,Bolesławiec,14040656.0,13789712,14863.0,20802,20431,0201
2,0201032,Gromadka,3549854.0,3573540,5317.0,14702,14800,0201
3,0201043,Nowogrodziec,9496560.0,9553744,15229.0,13732,13814,0201
4,0201052,Osiecznica,6054744.0,5844560,7288.0,18294,17659,0201
...,...,...,...,...,...,...,...,...
2406,3218013,Dobra,2055590.0,2010454,4353.0,10399,10170,3218
2407,3218023,Łobez,9301585.0,8834999,13815.0,14826,14083,3218
2408,3218032,Radowo Małe,1714278.0,1546533,3577.0,10553,9521,3218
2409,3218043,Resko,6718251.0,6612100,7885.0,18762,18466,3218
2410,3218053,Węgorzyno,3798230.0,3476544,6856.0,12199,11166,3218

Porównanie średnich dochodów gmin w latach 2019 i 2020

In [62]:
sr2019 = math.floor(df_gm['średni dochód 2019'].mean())
sr2020 = math.floor(df_gm['średni dochód 2020'].mean())
stosunek = round(sr2020/sr2019, 4)

print('W roku 2019 średni dochód w gminach wyniósł śrdnio: ' + str(sr2019) + ' a w 2020 roku: ' + str(sr2020) + '. \n' 
      'Stosunek dochodów w 2020 do 2019 roku wyniósł: ' + str(stosunek))

W roku 2019 średni dochód w gminach wyniósł śrdnio: 16490 a w 2020 roku: 16404.
Stosunek dochodów w 2020 do 2019 roku wyniósł: 0.9948

In [97]:
min2019 = df_gm['średni dochód 2019'].min()
min2020 = df_gm['średni dochód 2020'].min()
max2019 = df_gm['średni dochód 2019'].max()
max2020 = df_gm['średni dochód 2020'].max()

gmina_min2019 = df_gm[df_gm['średni dochód 2019'] == min2019]
gmina_min2020 = df_gm[df_gm['średni dochód 2020'] == min2020]
gmina_max2019 = df_gm[df_gm['średni dochód 2019'] == max2019]
gmina_max2020 = df_gm[df_gm['średni dochód 2020'] == max2020]

In [98]:
gmina_min2019

,id,gmina,dochody 2019,dochody 2020,populacja,średni dochód 2019,średni dochód 2020,id2
1538,2007062,Przytuły,445556.0,474958,2059.0,4765,5079,2007

In [99]:
gmina_min2020

,id,gmina,dochody 2019,dochody 2020,populacja,średni dochód 2019,średni dochód 2020,id2
1538,2007062,Przytuły,445556.0,474958,2059.0,4765,5079,2007

In [100]:
gmina_max2019

,id,gmina,dochody 2019,dochody 2020,populacja,średni dochód 2019,średni dochód 2020,id2
982,1405021,Podkowa Leśna,15040055.0,14454665,3801.0,87135,83744,1405

In [101]:
gmina_max2020

,id,gmina,dochody 2019,dochody 2020,populacja,średni dochód 2019,średni dochód 2020,id2
1609,2202032,Chojnice,15130423.0,97249563,19498.0,17088,109835,2202

Pełna tabela dla powiatów

In [67]:
df_pow

,id,powiat,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020,id2
0,0201,bolesławiecki,21981364,21276533,89762.0,20076,19432,17226821,13176111,20033,19432,1.002146,1.000000,02
1,0202,dzierżoniowski,21903272,21328692,99935.0,17968,17497,6420365,7500647,17930,17497,1.002119,1.000000,02
2,0203,głogowski,30342887,28916309,88447.0,28125,26803,83367864,68729943,28066,26802,1.002102,1.000037,02
3,0204,górowski,5783360,5682116,34552.0,13722,13482,5343284,6591940,13693,13481,1.002118,1.000074,02
4,0205,jaworski,10548367,10450783,49734.0,17388,17227,8074262,8360147,17351,17227,1.002132,1.000000,02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,3214,stargardzki,27891901,27801859,120132.0,19034,18973,37004842,46349334,18994,18972,1.002106,1.000053,32
310,3215,szczecinecki,15898766,15277345,77258.0,16871,16211,13814314,12742520,16835,16211,1.002138,1.000000,32
311,3216,świdwiński,8989043,8641304,46394.0,15884,15270,17604253,14744665,15851,15269,1.002082,1.000065,32
312,3217,wałecki,11272742,10931442,52707.0,17534,17003,13609681,12184599,17496,17002,1.002172,1.000059,32
313,3218,łobeski,6349165,6038431,36486.0,14266,13568,12331176,13504443,14235,13567,1.002178,1.000074,32

Porównanie średnich dochodów powiatów w latach 2019 i 2020

In [68]:
sr2019 = math.floor(df_pow['średni dochód 2019'].mean())
sr2020 = math.floor(df_pow['średni dochód 2020'].mean())
stosunek = round(sr2020/sr2019, 4)

print('W roku 2019 średni dochód w powiatach wyniósł średnio: ' + str(sr2019) + ' a w 2020 roku: ' + str(sr2020) + '. \n' 
      'Stosunek dochodów w 2020 do 2019 roku wyniósł: ' + str(stosunek))

W roku 2019 średni dochód w powiatach wyniósł średnio: 18411 a w 2020 roku: 18118.
Stosunek dochodów w 2020 do 2019 roku wyniósł: 0.9841

Średni stosunek średniego dochodu powiatów do dochodu estymowanego przez jednostki podrzędne

In [72]:
stosunek2019 = df_pow['porównanie 2019'].mean()
stosunek2020 = df_pow['porównanie 2020'].mean()

stosunek2019

1.0017857819871796

In [73]:
stosunek2020

0.9996750899450992

wariancje dochodu

In [76]:
var2019 = math.floor(df_pow['wariancja 2019'].mean())
var2019

29972039

In [77]:
var2020 = math.floor(df_pow['wariancja 2020'].mean())
var2020

33730395

In [102]:
min2019 = df_pow['średni dochód 2019'].min()
min2020 = df_pow['średni dochód 2020'].min()
max2019 = df_pow['średni dochód 2019'].max()
max2020 = df_pow['średni dochód 2020'].max()

powiat_min2019 = df_pow[df_pow['średni dochód 2019'] == min2019]
powiat_min2020 = df_pow[df_pow['średni dochód 2020'] == min2020]
powiat_max2019 = df_pow[df_pow['średni dochód 2019'] == max2019]
powiat_max2020 = df_pow[df_pow['średni dochód 2020'] == max2020]

In [103]:
powiat_min2019

,id,powiat,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020,id2
235,2603,kazimierski,3880229,4016879,33340.0,9541,9877,2408870,1790720,9521,9877,1.002101,1.0,26

In [104]:
powiat_min2020

,id,powiat,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020,id2
235,2603,kazimierski,3880229,4016879,33340.0,9541,9877,2408870,1790720,9521,9877,1.002101,1.0,26

In [105]:
powiat_max2019

,id,powiat,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020,id2
134,1418,piaseczyński,122938522,118824446,190606.0,52878,51109,522494112,398221086,52767,51108,1.002104,1.00002,14

In [106]:
powiat_max2020

,id,powiat,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020,id2
134,1418,piaseczyński,122938522,118824446,190606.0,52878,51109,522494112,398221086,52767,51108,1.002104,1.00002,14

Pełna tabela dla województw

In [80]:
df_woj

,id,wojewodztwo,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020
0,02,dolnośląskie,146521177,143787146,2891321,26615,26119,30525585,29674547,22772,22311,1.168760,1.170678
1,04,kujawsko-pomorskie,80114406,77938448,2061942,20406,19852,13134944,12620734,17515,17229,1.165059,1.152243
2,06,lubelskie,67219899,65228210,2095258,16849,16350,8943580,8321717,14108,13796,1.194287,1.185126
3,08,lubuskie,40309236,38895731,1007145,21020,20283,3982673,4189330,18703,18063,1.123884,1.122903
4,10,łódzkie,109394196,106927491,2437970,23566,23035,14507940,14352050,20316,19987,1.159972,1.152499
5,12,małopolskie,156151173,154769447,3410441,24047,23834,29788886,27782015,18989,18860,1.266365,1.263733
6,14,mazowieckie,389959220,380227237,5425028,37752,36810,114482022,111656785,26173,25703,1.442402,1.432129
7,16,opolskie,37165073,36183042,976774,19983,19455,3874481,3290733,18151,17674,1.100931,1.100769
8,18,podkarpackie,67137520,65682244,2121229,16623,16262,5203409,5061996,15043,14786,1.105032,1.099824
9,20,podlaskie,41529479,40759371,1173286,18590,18245,8452492,7736755,15161,14903,1.226172,1.224250
10,22,pomorskie,109946078,111320530,2346671,24607,24914,9027148,29680355,19011,20100,1.294356,1.239502
11,24,śląskie,224767214,218863771,4492330,26278,25587,13062037,12378338,24005,23585,1.094689,1.084884
12,26,świętokrzyskie,41001276,40133238,1224626,17584,17212,5529701,4889267,15678,15391,1.121572,1.118316
13,28,warmińsko-mazurskie,49259321,47344145,1416495,18264,17554,4033478,3885684,15941,15394,1.145725,1.140314
14,30,wielkopolskie,168811448,166394837,3496450,25357,24994,18722253,18902616,22233,22036,1.140512,1.134235
15,32,zachodniopomorskie,69267913,67677173,1688047,21551,21056,21213138,21136402,18708,18318,1.151967,1.149470

Porównanie średnich dochodów powiatów w latach 2019 i 2020

In [81]:
sr2019 = math.floor(df_woj['średni dochód 2019'].mean())
sr2020 = math.floor(df_woj['średni dochód 2020'].mean())
stosunek = round(sr2020/sr2019, 4)

print('W roku 2019 średni dochód w województwach wyniósł średnio: ' + str(sr2019) + ' a w 2020 roku: ' + str(sr2020) + '. \n' 
      'Stosunek dochodów w 2020 do 2019 roku wyniósł: ' + str(stosunek))

W roku 2019 średni dochód w województwach wyniósł średnio: 22443 a w 2020 roku: 21972.
Stosunek dochodów w 2020 do 2019 roku wyniósł: 0.979

Średni stosunek średniego dochodu województw do dochodu estymowanego przez jednostki podrzędne

In [82]:
stosunek2019 = df_woj['porównanie 2019'].mean()
stosunek2020 = df_woj['porównanie 2020'].mean()

stosunek2019

1.1813552814990391

In [83]:
stosunek2020

1.1731798497094315

średnie Wariancje dochodów powiatów podległych województwom

In [84]:
var2019 = math.floor(df_woj['wariancja 2019'].mean())
var2019

19030235

In [85]:
var2020 = math.floor(df_woj['wariancja 2020'].mean())
var2020

19722457

In [107]:
min2019 = df_woj['średni dochód 2019'].min()
min2020 = df_woj['średni dochód 2020'].min()
max2019 = df_woj['średni dochód 2019'].max()
max2020 = df_woj['średni dochód 2020'].max()

woj_min2019 = df_woj[df_woj['średni dochód 2019'] == min2019]
woj_min2020 = df_woj[df_woj['średni dochód 2020'] == min2020]
woj_max2019 = df_woj[df_woj['średni dochód 2019'] == max2019]
woj_max2020 = df_woj[df_woj['średni dochód 2020'] == max2020]

In [108]:
woj_min2019

,id,wojewodztwo,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020
8,18,podkarpackie,67137520,65682244,2121229,16623,16262,5203409,5061996,15043,14786,1.105032,1.099824

In [109]:
woj_min2020

,id,wojewodztwo,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020
8,18,podkarpackie,67137520,65682244,2121229,16623,16262,5203409,5061996,15043,14786,1.105032,1.099824

In [110]:
woj_max2019

,id,wojewodztwo,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020
6,14,mazowieckie,389959220,380227237,5425028,37752,36810,114482022,111656785,26173,25703,1.442402,1.432129

In [111]:
woj_max2020

,id,wojewodztwo,dochod 2019,dochod 2020,populacja,średni dochód 2019,średni dochód 2020,wariancja 2019,wariancja 2020,sr wazona 2019,sr wazona 2020,porównanie 2019,porównanie 2020
6,14,mazowieckie,389959220,380227237,5425028,37752,36810,114482022,111656785,26173,25703,1.442402,1.432129